site_name: BytePrep â€“ Data Engineering Interview Guide
site_url: https://anand-kumar4.github.io/byteprep-interview-guide/
repo_url: https://github.com/Anand-kumar4/byteprep-interview-guide
edit_uri: ""
theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - navigation.top

nav:
  - Home: index.md
  - SQL: sql/index.md
  - Python:
      - Overview: python/index.md
      - Core Concepts: python/core-concepts.md
      - Theory Questions: python/theory.md
      - Practical Coding: python/practical.md
      - DSA Concepts: python/dsa.md
  - PySpark: pyspark/index.md
  - AWS: aws/index.md
  - Data Modeling: data-modeling/index.md
  - System Design: system-design/index.md
  - Projects: projects/index.md
  - About: about.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
      toc_depth: 2
  - footnotes
  - tables
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.highlight

plugins:
  - search
  - minify:
      minify_html: true
  - meta-descriptions
  - awesome-pages

extra_javascript:
  - https://www.googletagmanager.com/gtag/js?id=G-VK6H53CHXQ
  - js/ga.js